<a href="https://colab.research.google.com/github/pvnmahathi/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Madagascar problem

In [37]:
import numpy as np

In [38]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])

In [39]:
# 4x3 . 3x1 = 4x1

In [40]:
y = np.matmul(A,x) - 4.0

In [41]:
y

array([[-2.356],
       [-1.19 ],
       [ 0.24 ],
       [ 0.7  ]])

In [42]:
Z = np.hstack((A,y))

In [43]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [44]:
S = np.array(np.arange(1,len(A)+1).reshape(4,1), dtype=np.int16)  #array of serial numbers to index the data

In [45]:
S

array([[1],
       [2],
       [3],
       [4]], dtype=int16)

In [46]:
F = np.hstack((S, Z)) #adding a column at the beginning of the data(similar to a serial no.)

In [47]:
F

array([[ 1.000e+00,  2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 2.000e+00,  3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 3.000e+00,  5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 4.000e+00,  7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [48]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))

  #### Code to return only records of citizens with high risk factor
  S = np.array(np.arange(1,len(A)+1).reshape(4,1), dtype=np.int16) #array of serial numbers to index the data
  F = np.hstack((S, L)) #adding a column at the beginning of the data(similar to a serial no.)
  P = F[F[:,-1]>0, :]  #returning records of high risk people by checking the weighted sum of all records and selecting records with risk-factor > 4
  return P 

In [49]:
print (RankArray(A,x))  #prints the records of citizens with high risk factor(in this instance last two records)

[[3.0e+00 5.0e+01 2.2e+02 6.5e+01 2.4e-01]
 [4.0e+00 7.0e+01 3.0e+02 3.0e+01 7.0e-01]]
